### ISSUE TITLE
[ADD] Docker Compose setup to prevent Python version conflicts.

### ISSUE THREAD

**Issue by dnh4** [iTeam-S/Ampalibe#107]
**Describe the bug**
There is a problem of versioning python, and the developper need to have the same env versioning.

**To Reproduce**
Make your defaut python version to python 1 or python 2:

**Expected behavior**
Some syntax like the decorator is not implemented yet

 - OS: [e.g. Windows/Linux/]
 - Ampalibe Version [e.g. 1.0.4]

Solution: https://github.com/dnh4/Ampalibe

**Comment by gaetan1903** [comment]
Like mentioned in the README,  Ampalibe required python 3.7+ to work.
