### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by jullury16** [iTeam-S/Ampalibe#57]
Add middleware for processing messages from user before handling them on the appropriated ampalibe action or command
It will be useful for interrupting process depending on the user message, like swear word warning, or switching action depending on what user input

**Comment by gaetan1903** [comment]
https://github.com/iTeam-S/Ampalibe/pull/68 voici une solution pour cet issue, en attente de release pour la 1.1.6.

utilisation du décorateur before_receive 

![image](https://user-images.githubusercontent.com/43904633/204442913-05a9eb42-6078-4e67-9f6a-f99693b20d26.png)
