### ISSUE TITLE
[BUG] Error connection with PostgreSQL

### ISSUE THREAD

**Issue by maminiainalaic** [iTeam-S/Ampalibe#96]
It raises an error when connecting with psycopg2 

![Capture d’écran 2023-04-02 142305](https://user-images.githubusercontent.com/126385570/229351038-970cac83-cd45-48ee-a060-7da607a57440.jpg)

And when i execute too this on my database it raises the same error:
 CREATE TABLE IF NOT EXISTS  "amp_user" (
                    id SERIAL,
                    user_id VARCHAR NULL DEFAULT NULL,
                    action TEXT NULL DEFAULT NULL,
                    last_use TIMESTAMP NULL DEFAULT NOW(),
                    lang VARCHAR NULL DEFAULT NULL,
                    PRIMARY KEY (id),
                    UNIQUE (user_id),
                    INDEX (last_use)
                )
![Capture d’écran 2023-04-02 143616](https://user-images.githubusercontent.com/126385570/229351175-16b0d428-3606-4aee-a6af-ce7028cbeb14.jpg)

 -PostgresSQL Version 15.2
 - OS: Linux
 - Ampalibe Version 1.1.8

**Comment by maminiainalaic** [comment]
??

**Comment by rivo2302** [comment]
@maminiainalaic 

💥 There was a syntax error in the creation of the `amp_user` table for **PostgreSQL** databases, but it has now been fixed. 👍 I am sending the pull request. 🚀

**Comment by gaetan1903** [comment]
> pip install https://github.com/iTeam-S/Ampalibe/archive/refs/tags/1.1.9.patch.zip
