### ISSUE TITLE
[BUG] SEND_ACTION  FAILED 

### ISSUE THREAD

**Issue by rivo2302** [iTeam-S/Ampalibe#99]
**Description**
The Function  `send_action`  doesn't work , Facebook may change the Messenger API.

**Error** 
```python
ERROR|Ampalibe:
  status_code : 400, data :{"error":{"message":"(#100) Sender action failed","type":"OAuthException","code":100,"error_subcode":2018048,"fbtrace_id":"AzvYcgDsCXhMQhr2K7JQIua"}}
```

**Comment by gaetan1903** [comment]
the endpoint seems to need  a pageid now,

the best approach is to get pageid via access token and store in the object,

after that, we can use it in all function..

**Comment by rivo2302** [comment]
The bug seems to have resolved itself 😂😂 , Facebook has left its code as it was before, finally.
